FROM ubuntu:22.04

ARG CHANGE_SOURCE=false
ARG IN_CHINA=false
ARG LARADOCK_PHP_VERSION=${PHP_VERSION}

## for apt to be noninteractive
ENV DEBIAN_FRONTEND noninteractive
ENV DEBCONF_NONINTERACTIVE_SEEN true
ENV TIME_ZOME Asia/Shanghai
ENV LARADOCK_PHP_VERSION=${LARADOCK_PHP_VERSION}

EXPOSE 80 443 9000
WORKDIR /var/www/html
# WORKDIR /app
CMD ["/opt/run.sh"]

COPY ./root/opt/build.sh /opt/build.sh
RUN bash /opt/build.sh

ONBUILD COPY ./root/ /
ONBUILD RUN bash /opt/onbuild.sh
