#!/usr/bin/env bash

echo_time() {
	echo "#### $(date +%F-%H:%M:%S) $*"
}

main() {
	# set -x
	export LANG='en_US.UTF-8'
	# export LC_CTYPE='en_US.UTF-8'
	# export LC_ALL='en_US.UTF-8'
	REPOS="$1" # 仓库的路径
	REV="$2"   # 新提交的版本号

	## found lock file, just wait
	lock_myself=/tmp/svn.lock.myself
	while [ -f $lock_myself ]; do sleep 2; done

	exec &> >(tee -a "/tmp/svn.post.commit.log")
	touch $lock_myself
	trap 'rm -f "$lock_myself"; exit $?' INT TERM EXIT

	## trap: do some work
	## dirs-changed result: trunk/path/to/some/, not include repo url $REPOS
	## REPOS result: REPOS=/var/www/usvn/files/svn/${repo_name}
	for path in $(/usr/bin/svnlook dirs-changed "$REPOS"); do
		repo_name="${REPOS#/var/www/usvn/files/svn/}"
		repo_name="${repo_name%/}"
		echo "$path" | tee -a "/var/www/svn_commit/svn_need_update.${REV}.$repo_name"
		## 交由 usvn docker 内的 run.sh 执行 svn update
		## https://gitee.com/xiagw/laradock/blob/in-china/usvn/run.sh
	done
	echo_time "Repository: $REPOS"
	echo_time "Revision: $REV"
	echo_time "Author: $(/usr/bin/svnlook author -r "$REV" "$REPOS") "
	echo_time "Commit message: $(/usr/bin/svnlook log -r "$REV" "$REPOS")"
	/usr/bin/svnlook diff -r "$REV" "$REPOS"
	## trap: end some work

	rm $lock_myself
	trap - INT TERM EXIT
}

main "$@"
