#!/usr/bin/env bash

echo_time() {
	echo "$(date +%F-%H:%M:%S) $*"
}

main() {
	# set -x
	REPOS="$1" # 仓库的路径
	REV="$2"   # 新提交的版本号
	export LANG='en_US.UTF-8'
	# export LC_CTYPE='en_US.UTF-8'
	# export LC_ALL='en_US.UTF-8'
	lock_myself=/tmp/svn.lock.myself
	exec &> >(tee -a "/tmp/svn.post.$(date +%F).log")
	## found lock, just wait
	while [ -f $lock_myself ]; do sleep 2; done
	touch $lock_myself
	trap 'rm -f "$lock_myself"; exit $?' INT TERM EXIT

	## trap: do some work
	## dirs-changed result: vrupup.com/path/to/some/, not include repo url /vrupup/svn/trunk
	## REPOS result: REPOS=/vrupup/svn/trunk
	for p in $(/usr/bin/svnlook dirs-changed "$REPOS"); do
		echo "$p" | tee -a "/tmp/svn_need_update.${REV}.${REPOS##*/}"
		## 交由 usvn docker 内的 run.sh 执行 svn update
		## https://gitee.com/xiagw/laradock/blob/in-china/usvn/run.sh
	done
	echo_time "**************************************************************"
	echo_time "提交版本：$REV 作者：$(/usr/bin/svnlook author -r "$REV" "$REPOS") REPO: $REPOS"
	echo_time "提交备注：$(/usr/bin/svnlook log -r "$REV" "$REPOS")"
	/usr/bin/svnlook diff -r "$REV" "$REPOS"
	## trap: end some work

	rm $lock_myself
	trap - INT TERM EXIT
}

main "$@"
