FROM nginx:alpine

# If you're in China, set IN_CHINA to true.
ARG CHANGE_SOURCE=false
ARG AUTO_UPGRADE=1

ENV LE_CONFIG_HOME /acmedata
ENV AUTO_UPGRADE $AUTO_UPGRADE

COPY ./root/ /
RUN sh /opt/build.sh

# WORKDIR /app

EXPOSE 80 81 443
