services:

    redis:
      image: ${MIRROR}redis:${REDIS_VERSION}
      restart: always
      build:
        context: ./redis
        args:
          - REDIS_VERSION=${REDIS_VERSION}
      volumes:
        - ${DATA_PATH_HOST}/redis:/data
      command: --requirepass ${REDIS_PASSWORD:-secret} --databases ${REDIS_DATABASES:-256} --appendonly yes --appenddirname appendonlydir
      ports:
        - "${REDIS_PORT}:6379"
      networks:
        - backend
